# Generated by Django 4.1.7 on 2023-04-04 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='img',
        ),
        migrations.AddField(
            model_name='activities',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Activity date'),
        ),
        migrations.AddField(
            model_name='activities',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Trip Date'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
