# Generated by Django 4.1.7 on 2023-04-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_city_activities_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='duration',
            new_name='days',
        ),
    ]
