# Generated by Django 4.1.7 on 2023-04-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_posts_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=250)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.posts')),
            ],
        ),
    ]
