# Generated by Django 4.1.7 on 2023-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_posts_description_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='notes',
            field=models.TextField(default=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.DateField(default=False, verbose_name='Trip Date'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='notes',
            field=models.TextField(default=False, max_length=250),
        ),
    ]
