# Generated by Django 4.1.7 on 2023-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.TextField(default='No comment', max_length=250),
        ),
    ]
