# Generated by Django 4.1.7 on 2023-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_photo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
