# Generated by Django 4.1.7 on 2023-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_posts_title_alter_posts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
