# Generated by Django 4.1.7 on 2023-04-10 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_posts_title_photo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-url']},
        ),
        migrations.AddField(
            model_name='photo',
            name='time',
            field=models.TimeField(default=datetime.time(0, 51, 48, 286785)),
        ),
    ]
