# Generated by Django 4.1.7 on 2023-04-10 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_photo_options_photo_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='time',
            field=models.TimeField(default=datetime.time(1, 36, 46, 316239)),
        ),
    ]
